# Teleop configuration for PS4 joystick using the x-pad configuration.
teleop_twist_joy:
  axis_linear:
    x: 1
    y: 0
  scale_linear:
    x: 1.0
    y: 1.0
  axis_angular:
    yaw: 3
  scale_angular:
    yaw: 0.75
  enable_button: 5
  enable_turbo_button: 9
joy_node:
  deadzone: 0.25
  autorepeat_rate: 20
